# Simple workflow for deploying static content to GitHub Pages
name: Deploy DocC

on:
  # Runs on new releases
  release:
    types: [published]
  push:
    branches: [docc_deploy, main]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    # Will only publish if the new release matches with the latest main branch commit.
    if: ${{ github.event.release.prerelease == false && github.event.release.draft == false }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-12
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - name: Build DocC
        run: |
          sh -e doc_gen/dl_framework.sh AgoraChat
          sh -e doc_gen/move_header_files.sh AgoraChat.xcframework
          sh -e doc_gen/headers_to_xcodeproj.sh AgoraChat docc_builder
          xcodebuild -project docc_builder/AgoraChat.xcodeproj docbuild -scheme AgoraChat -derivedDataPath /tmp/docbuild -destination generic/platform=iOS
          $(xcrun --find docc) process-archive \
            transform-for-static-hosting /tmp/docbuild/Build/Products/Debug-iphoneos/AgoraChat.doccarchive \
            --hosting-base-path AgoraChat_iOS \
            --output-path docs;
          echo "<script>window.location.href += \"/documentation/agorachat\"</script>" > docs/index.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload docs directory
          path: 'docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
